---
- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: Wait for Grafana to start
  wait_for:
    port: 3000
    timeout: 30

- name: Create Prometheus datasource
  community.grafana.grafana_datasource:
    name: "datasource-prometheus"
    grafana_url: "http://localhost:3000"
    grafana_user: "{{ grafana_admin_username }}"
    grafana_password: "{{ grafana_admin_password }}"
    org_id: "1"
    ds_type: "prometheus"
    ds_url: "http://localhost:9090"
