---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running and enabled
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Copy React build files to Nginx web root
  copy:
    src: /home/jenkins/workspace/java-pipeline/frontend/build/  
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes

- name: Configure Nginx to serve React app
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          server_name _;

          root /var/www/html;
          index index.html index.htm;

          location / {
              try_files $uri /index.html;
          }
      }

- name: Reload Nginx to apply the new configuration
  systemd:
    name: nginx
    state: reloaded
