all:
  hosts:
    frontend:
      ansible_host: 98.81.218.231
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/jenkins/workspace/java-pipeline/terraformAWS/key/my_ssh_key
      
    backend:
      ansible_host: 3.89.225.76
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/jenkins/workspace/java-pipeline/terraformAWS/key/my_ssh_key

    database:
      ansible_host: 98.81.129.52
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/jenkins/workspace/java-pipeline/terraformAWS/key/my_ssh_key

  children:
    frontend_group:
      hosts:
        frontend

    backend_group:
      hosts:
        backend

    database_group:
      hosts:
        database
