all:
  hosts:
    frontend:
      ansible_host: "{{ lookup('env', 'FRONTEND_IP') }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/jenkins/workspace/java-pipeline/terraformAWS/key/my_ssh_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    backend:
      ansible_host: "{{ lookup('env', 'BACKEND_IP') }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/jenkins/workspace/java-pipeline/terraformAWS/key/my_ssh_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    database:
      ansible_host: "{{ lookup('env', 'DATABASE_IP') }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: /home/jenkins/workspace/java-pipeline/terraformAWS/key/my_ssh_key
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    frontend_group:
      hosts:
        frontend

    backend_group:
      hosts:
        backend

    database_group:
      hosts:
        database
