    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.53.2/prometheus-2.53.2.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.53.2.linux-amd64.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus-2.53.2.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Prometheus binary to /usr/local/bin
      command: mv /tmp/prometheus-2.53.2.linux-amd64/prometheus /usr/local/bin/
      args:
        removes: /usr/local/bin/prometheus

    - name: Move Promtool binary to /usr/local/bin
      command: mv /tmp/prometheus-2.53.2.linux-amd64/promtool /usr/local/bin/
      args:
        removes: /usr/local/bin/promtool

    - name: Create directories for Prometheus configuration and data
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Create prometheus user
      user:
        name: prometheus
        shell: /bin/false
        system: yes

    - name: Set ownership of data directory
      command: chown prometheus:prometheus /var/lib/prometheus

    - name: Create Prometheus configuration file
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Create systemd service file for Prometheus
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/usr/local/bin/consoles \
            --web.console.libraries=/usr/local/bin/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes
