---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - wget
      - tar
    state: present

- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin

- name: Create directories for Prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Prometheus binaries
  command: mv /tmp/prometheus-2.45.0.linux-amd64/{prometheus,promtool} /usr/local/bin/

- name: Set ownership of Prometheus binaries
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /usr/local/bin/prometheus
    - /usr/local/bin/promtool

- name: Move Prometheus config files
  command: mv /tmp/prometheus-2.45.0.linux-amd64/{consoles,console_libraries,prometheus.yml} /etc/prometheus/

- name: Set ownership of Prometheus config directories
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    recurse: yes
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Configure Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started
