---
    - name: Завантаження останньої версії Prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.53.2/prometheus-2.53.2.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.53.2.linux-amd64.tar.gz

    - name: Розпакування архіву Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus-2.53.2.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Створення користувача Prometheus
      ansible.builtin.user:
        name: prometheus
        shell: /bin/false
        system: yes
        create_home: no

    - name: Переміщення бінарних файлів у /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/prometheus-2.53.2.linux-amd64/prometheus
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    - name: Переміщення promtool у /usr/local/bin
      ansible.builtin.copy:
        src: /tmp/prometheus-2.53.2.linux-amd64/promtool
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'

    - name: Створення директорій для Prometheus
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Копіювання конфігураційного файлу Prometheus
      ansible.builtin.copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Створення systemd сервісу для Prometheus
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/usr/local/bin/consoles \
            --web.console.libraries=/usr/local/bin/console_libraries

          [Install]
          WantedBy=multi-user.target

    - name: Перезавантаження systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Запуск Prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: started
        enabled: yes
