- name: Create Prometheus user and group
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin

- name: Create Prometheus config directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create Prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Download Prometheus v2.53.2
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.53.2/prometheus-2.53.2.linux-amd64.tar.gz
    dest: /tmp/prometheus-2.53.2.linux-amd64.tar.gz

- name: Extract Prometheus archive
  unarchive:
    src: /tmp/prometheus-2.53.2.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Prometheus binary to /usr/local/bin
  command: mv /tmp/prometheus-2.53.2.linux-amd64/prometheus /usr/local/bin/

- name: Move Promtool binary to /usr/local/bin
  command: mv /tmp/prometheus-2.53.2.linux-amd64/promtool /usr/local/bin/

- name: Move Prometheus config file
  copy:
    src: /tmp/prometheus-2.53.2.linux-amd64/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create Prometheus systemd service file
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Service
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/ --web.console.templates=/usr/share/prometheus/console_libraries --web.console.libraries=/usr/share/prometheus/consoles

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to apply Prometheus service
  systemd:
    daemon_reload: yes

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started
