- name: Update apt cache
  apt:
    update_cache: yes

- name: Add PostgreSQL APT repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main"
    state: present
    filename: 'pgdg.list'
    update_cache: yes

- name: Import PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL
  apt:
    name: postgresql-14
    state: present

- name: Ensure PostgreSQL is running
  systemd:
    name: postgresql
    enabled: yes
    state: started

- name: Install GNU GPG (required for MongoDB key)
  apt:
    name: gnupg
    state: present

- name: Add MongoDB GPG key to apt keyring
  apt_key:
    url: https://pgp.mongodb.com/server-7.0.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64, signed-by=/usr/share/keyrings/mongodb-server-7.0.asc ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse"
    state: present

- name: Update apt cache again to include MongoDB
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Ensure MongoDB is running
  systemd:
    name: mongod
    enabled: yes
    state: started

- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Ensure Redis is running
  systemd:
    name: redis-server
    enabled: yes
    state: started

- name: Configure PostgreSQL to listen on all addresses
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf  
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted

- name: Configure pg_hba.conf for remote access
  lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf  
    line: "host    all             all             0.0.0.0/0         md5"
    state: present

- name: Change PostgreSQL user password
  become: true
  become_user: postgres
  shell: psql -c "ALTER USER postgres PASSWORD 'password';"

- name: Create PostgreSQL database
  become: true
  become_user: postgres
  postgresql_db:
    name: postgres_db
    state: present

- name: Configure Redis to bind to all addresses
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?bind'
    line: "bind 0.0.0.0"

- name: Restart Redis
  systemd:
    name: redis-server
    state: restarted
