global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  

  - job_name: 'ec2-node-exporter'
    static_configs:
      - targets: ['{{ frontend_ip }}:9100']
      - targets: ['{{ backend_ip }}:9100']
