all:
  hosts:
    frontend:
      ansible_host: "{{ frontend_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"
      
    backend:
      ansible_host: "{{ backend_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"

    database:
      ansible_host: "{{ database_ip }}"
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"

  children:
    frontend_group:
      hosts:
        frontend

    backend_group:
      hosts:
        backend

    database_group:
      hosts:
        database
